feature/cryptography
facily-tech/go-core pull request #10
Opened 2021-12-29 21:13 UTC by NaiaraPf

first commit

2021-12-29 22:47 UTC, roger-russel commented
Cria um link simbólico do arquivo ".golangci.yml" que está na raiz do multirepo para dentro do seu projeto, por favor.
Assim já irá pegar a mesma configuração de lint dos outros projetos.

2022-01-03 13:26 UTC, dvdscripter approved these changes

2022-01-03 14:36 UTC, roger-russel requested changes
request changes

2022-01-05 12:40 UTC, roger-russel requested changes

2022-01-05 12:40 UTC, roger-russel commented on cryptography/cryptography.go
> +// ICryptography is Cryptography interface to use when you wanna make a default setup on its methods.
aqui, coloca a linha do generate por favor:

//go:generate mockgen -source=/cryptography/cryptography.go -destination=/cryptography/cryptography_mock.go -package=cryptography

2022-01-05 20:32 UTC, roger-russel approved these changes

2022-01-07 12:57 UTC, roger-russel approved these changes

2022-01-07 13:14 UTC, juniorrosul approved these changes

2022-01-07 13:15 UTC, samuelmachado approved these changes

2022-01-07 14:02 UTC, andersonfacily approved these changes

2022-01-07 17:03 UTC, merged